[package]
name = "ncnn-nanodet-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncnn-rs = { path = "../rust-ncnn/ncnn-rs" }
opencv = "0.68"
anyhow = "1.0"
